# action.yml
name: "Deploy Model to Algorithmia"
description: "TBD"
branding:
  icon: "alert-circle"
  color: "yellow"
inputs:
  algorithmia_api_key:
    description: "Algorithmia API key"
    required: true
  current_repo:
    description: "Repo path to be used by actions/checkout@v2, to mount the workflow workspace to /github/workspace/"
    required: true
  notebook_path:
    description: "Path of the notebook to be executed by this action"
    required: false
  modelfile_relativepath:
    description: "TBD"
    required: true
  algorithmia_uploadpath:
    description: "TBD"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.algorithmia_api_key }}
    - ${{ inputs.current_repo }}
    - ${{ inputs.notebook_path }}
    - ${{ inputs.modelfile_relativepath }}
    - ${{ inputs.algorithmia_uploadpath }}
    
